package com.spaneos.vemas.util;

public interface SQLQueries {
	String ADD_VENDOR = "INSERT INTO VENDOR(VENDORTYPE,VENDORCATEGORY,VENDORNAME,MOBILE,LANDLINE,WEBSITE,ADDRESS) VALUES(?,?,?,?,?,?,?)";
	String ADD_CONTACT = "INSERT INTO CONTACT(CONTACTNAME,DESIGNATION,MOBILE,EMAIL,EMPLOYEMENTSTATUS,REPORTINGMANAGER,VENDORID) VALUES(?,?,?,?,?,?,?)";
	String ADD_USER = "INSERT INTO USER(FIRSTNAME,MIDDLENAME,LASTNAME, EMAIL, PASSWORD, SELECT_QUESTION, ANSWER, MOBILE) VALUES(?,?,?,?,?,?,?,?)";
	String GET_VENDORS_BY_VENDORNAME = "SELECT * FROM VENDOR WHERE VENDORNAME LIKE ?";
	String GET_VENDORS_BY_VENDORMOBILE = "SELECT * FROM VENDOR WHERE MOBILE=?";
	String GET_CONTACTS_BY_VENDORID = "SELECT * FROM CONTACT WHERE VENDORID=?";
	String UPDATE_VENDOR_BY_VENDORID = "UPDATE VENDOR SET VENDORTYPE=?,VENDORCATEGORY=?,VENDORNAME=?,MOBILE=?,LANDLINE=?,WEBSITE=?,ADDRESS=? WHERE VENDORID=?";
	String UPDATE_CONTACT_BY_EMAIL = "UPDATE CONTACT SET CONTACTNAME=?,DESIGNATION=?,MOBILE=?,EMPLOYMENTSTATUS=?,REPORTINGMANAGER=? WHERE EMAIL=?";
	String GET_PASSWORD_BY_EMAIL = "SELECT PASSWORD,SELECT_QUESTION,ANSWER FROM USER WHERE EMAIL=?";
	String GET_ALL_USERS = "SELECT * FROM USER";
	String DELETE_VENDOR = "DELETE FROM VENDOR WHERE VENDORNAME=?";
	String DELETE_CONTACT = "DELETE FROM CONTACT WHERE EMAIL=?";
	String GET_ALL_VENDORS = "SELECT * FROM VENDOR";
	String GET_USER_BY_EMAIL = "SELECT * FROM USER where EMAIL = ?";
	String GET_CONTACTS_BY_VENDORNAME = "SELECT C.CONTACTID,C.CONTACTNAME,C.DESIGNATION,C.MOBILE,C.EMAIL,C.EMPLOYEMENTSTATUS,C.REPORTINGMANAGER FROM VENDOR AS V, CONTACT AS C  WHERE V.VENDORNAME LIKE ? AND V.VENDORID = C.VENDORID";
	
	
	//CREATEING THE TABLES:
	
	String CREATE_TABLE_VENDOR=" CREATE TABLE CONTACT(CONTACTID INT PRIMARY KEY AUTO_INCREMENT,CONTACTNAME VARCHAR(200),DESIGNATION VARCHAR(200),MOBILE VARCHAR(200),EMAIL VARCHAR(200),EMPLOYEMENTSTATUS VARCHAR(200),REPORTINGMANAGER VARCHAR(200),VENDORID INT,FOREIGNKEY(VENDORID) REFERENCES VENDOR(VENDORID));";
	String CREATE_TABLE_USER="CREATE TABLE CONTACT(CONTACTID INT PRIMARY KEY AUTO_INCREMENT,CONTACTNAME VARCHAR(200),DESIGNATION VARCHAR(200),MOBILE VARCHAR(200),EMAIL VARCHAR(200),EMPLOYEMENTSTATUS VARCHAR(200),REPORTINGMANAGER VARCHAR(200),VENDORID INT,FOREIGNKEYVENDORID) REFERENCES VENDOR(VENDORID));";
	String CREATE_TABLE_CONTACT = "CREATE TABLE CONTACT(CONTACTID INT PRIMARY KEY AUTO_INCREMENT,CONTACTNAME VARCHAR(200),DESIGNATION VARCHAR(200),MOBILE VARCHAR(200),EMAIL VARCHAR(200),EMPLOYEMENTSTATUS VARCHAR(200),REPORTINGMANAGER VARCHAR(200),VENDORID INT,FOREIGNKEY(VENDORID) REFERENCES VENDOR(VENDORID))";
}